### ISSUE TITLE
Custom Dialog

### ISSUE THREAD

**Issue by douglasalipio** [MkhytarMkhoian/ConductorDialog#1]
Hi, a really nice piece of code. I'd like to know how can I create a custom Dialog. I was looking for the demo and I saw just a classic alert. So, is it possible to use that?

**Comment by MkhytarMkhoian** [comment]
Hi, in the demo you can see a fully custom progress dialog. You can do all customization you need

**Comment by douglasalipio** [comment]
@MkhytarMkhoian Thanks!
